### ISSUE TITLE
fails on port numbers with 5 digits

### ISSUE THREAD

**Issue by alphaone** [cburgmer/tinycors#1]
Hallo Christoph,

something seems off, while trying to parse port numbers with 5 digits.

Cheers,
Torsten

```
% tinycors --port 17100 http://leader.mesos.something.org:17100
Listening on http://localhost:17100
/usr/local/lib/node_modules/tinycors/node_modules/http-proxy/lib/node-http-proxy/routing-proxy.js:315
    throw new Error('options.host and options.port or options.target are requi
          ^
Error: options.host and options.port or options.target are required.
    at RoutingProxy._getKey (/usr/local/lib/node_modules/tinycors/node_modules/http-proxy/lib/node-http-proxy/routing-proxy.js:315:11)
    at RoutingProxy.proxyRequest (/usr/local/lib/node_modules/tinycors/node_modules/http-proxy/lib/node-http-proxy/routing-proxy.js:225:18)
    at Array.<anonymous> (/usr/local/lib/node_modules/tinycors/tinycors.js:33:11)
    at Server.handler (/usr/local/lib/node_modules/tinycors/node_modules/http-proxy/lib/node-http-proxy.js:175:40)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
```

**Comment by cburgmer** [comment]
Hmm, funny. If you don't beat me to it, I'll try to find out why :)

**Comment by alphaone** [comment]
Stupid Me. It was the `http://` in front of the host ... not the five digit portnumber

**Comment by alphaone** [comment]
It's working perfectly well

**Comment by cburgmer** [comment]
Didn't spot this in the example above if that makes it any better :)
